Basic Of Python
Variable Datatypes in Python
Variable
Variables Assignment 
Print Formatting

In [1]:
1+1

2

In [2]:
4*5

20

In [3]:
10/2

5.0

In [4]:
10**2

100

In [5]:
type(1)

int

In [6]:
type("hello")

str

In [7]:
type(1.5)

float

In [8]:
type(5+5j)

complex

In [9]:
type(True) # Fall under reserved keyword

bool

In [10]:
type('hello')# so singlw or double quotes both fine for string

str

In [14]:
a=5
b=6
print(a*b)
print(a/b)
print(a**b)
print(a%b)

30
0.8333333333333334
15625
5


In [15]:
first_name="Aditya"
last_name="Singh Rjaput"

In [17]:
print("My first name is {} and last name is {}".format(first_name,last_name))

My first name is Aditya and last name is Singh Rjaput


In [18]:
print("My first name is {} and last name is {}".format(last_name,first_name))

My first name is Singh Rjaput and last name is Aditya


In [20]:
print("My first name is {first} and last name is {last}".format(first=first_name,last=last_name))

My first name is Aditya and last name is Singh Rjaput


In [21]:
print("My first name is {first} and last name is {last}".format(last=last_name,first=first_name))

My first name is Aditya and last name is Singh Rjaput


In [22]:
#In above 4 example we can see how important is defining a Order 

In [23]:
len("aditya")#Inbuilt function for counting charachetr

6

In [25]:
type([1,2,3,4,5])


list

#why Python
-Because with python we can do multiple work very easily compare to other language
-Syntax is very much simple
-Multiple Library and Framework that developer can use to develop multiple 
-numpy-To deal with multidimensional array
-pandas-to retrieve multiple dataset
-seaborn-statstical analysis
-scikits Library-ML Algorithm (Supervised,Unsupervised)
-Deeplearning(Subset of ML)
-WEB service,Webapp
Pyhton having community and Cooperate support
-various Github opensource projects 
-Product google assistant,Alexa,nETFLIX MOVIE Recommendation and allusing python

#Day 2
##Python Data Structures and Boolean
-boolean
-boolean and logical operators
-lists
-comparision Operators
-Dictionaries
-Tuples
-Sets


In [27]:
##Boolean Variables
print(True,False)

True False


In [29]:
type(True)

bool

In [30]:
type(False)

bool

In [31]:
my_str="adiya_singh"

In [38]:
print(my_str.isalpha())
print(my_str.isalnum())
print(my_str.isdigit())
print(my_str.istitle())
print(my_str.isupper())
print(my_str.islower())
print(my_str.isspace())
print(my_str.endswith('h'))#Case_Sensitive
print(my_str.startswith('a'))#Case_Sensitive

False
False
False
False
False
True
False
True
True


Boolean and Logical Operators

In [39]:
True and True

True

In [40]:
True and False

False

In [41]:
True or True

True

In [42]:
False or False

False

In [43]:
True or False

True

In [44]:
True and False

False

Lists
A List is a datastructure that is a mutable , ordered sequence of elements each element of value that is inside the list is called and item.Just as strings are defined as charecters between quotes,lists are defined by having values between square Brackets[]



In [45]:
type([])

list

In [47]:
lst=list()

In [49]:
type(lst)

list

In [51]:
lst=['M','c','b',100,1.5,5+6j,[1,2,3]]

In [52]:
type(lst)

list

Append


In [54]:
lst.append(100) #Used to add elements in the list

In [55]:
lst

['M', 'c', 'b', 100, 1.5, (5+6j), [1, 2, 3], 100]

In [ ]:
#indexing in list start with 0 to ++ from left to right and starts from -1 from right to left

In [62]:
lst[0]

'M'

In [63]:
lst[0:]#if will not anything in end will pick all from start index 

['M', 'c', 'd', 'c', 'b', 100, 1.5, (5+6j), [1, 2, 3], 100]

In [64]:
lst[1:4] # will show data 1 2 3 index value

['c', 'd', 'c']

In [65]:
lst[:4]

['M', 'c', 'd', 'c']

In [66]:
lst[-1]

100

In [67]:
lst[3:-1]

['c', 'b', 100, 1.5, (5+6j), [1, 2, 3]]

In [70]:
lst[-1]

100

In [71]:
lst[-3:-1]

[(5+6j), [1, 2, 3]]

In [72]:
lst[-4:]

[1.5, (5+6j), [1, 2, 3], 100]

Insert

In [59]:
#inserts in a specific order
lst.insert(2,'c')
lst.insert(2,'d')

In [60]:
lst

['M', 'c', 'd', 'c', 'b', 100, 1.5, (5+6j), [1, 2, 3], 100]

Extend Method

In [73]:
lst=[1,2,3,4,5,6]

In [74]:
lst.extend([4,5,6])

In [75]:
lst

[1, 2, 3, 4, 5, 6, 4, 5, 6]

Various Operation that we can Perform in List

In [76]:
sum(lst)

36

Pop()Method - To Remove last element by default

In [77]:
lst.pop()

6

In [78]:
lst

[1, 2, 3, 4, 5, 6, 4, 5]

In [79]:
lst.pop(1)  #iF WANT TO remove specific then input there indexing

2

In [80]:
lst

[1, 3, 4, 5, 6, 4, 5]

In [85]:
#Count()-To count the total occurence of list
lst=[1,2,3,4,5,6,1]
lst.count(1)

2

In [86]:
len(lst)

7

In [92]:
#Index function will find the first occurence of that value
lst.index(1,1,7)

6

In [93]:
lst.index(1,0,7)

0

In [95]:
#Min and Max 
min(lst)

1

In [96]:
max(lst)

6

In [97]:
lst*2 #whole list appended by 2

[1, 2, 3, 4, 5, 6, 1, 1, 2, 3, 4, 5, 6, 1]

Sets/Dictopnaries/Tuples

SETS
A Set is an unordered collection data type that is Iterable, mutable, and has no duplicate elements. Python's set class
represents the mathematical notion of a set. This is based on a data structure known as a hash table

In [100]:
set_var=set()
print(set_var)
print(type(set_var))

set()
<class 'set'>


In [101]:
set_var={1,2,3,4,5,6}

In [102]:
set_var

{1, 2, 3, 4, 5, 6}

In [103]:
set_var[0] #so Set is not subscriptable also cant support indexing


TypeError: 'set' object is not subscriptable

In [104]:
set_var.add("hulk")

In [105]:
set_var

{1, 2, 3, 4, 5, 6, 'hulk'}

In [118]:
set1={"Avengers","TronMan","Hàtman"}
set2={"Avengers" , "TronMan", "Hàtman", "Hu1k2"}

In [113]:
set2.difference(set1)

{'Hu1k2'}

In [114]:
set2

{'Avengers', 'Hu1k2', 'Hàtman', 'TronMan'}

In [115]:
set2.difference_update(set1)

In [116]:
set2

{'Hu1k2'}

In [119]:
set2.intersection(set1) # to find common but again once will use update then will be updated

{'Avengers', 'Hàtman', 'TronMan'}

Dictionaries
A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets,
and they have keys and values.

In [122]:
dic={}

In [123]:
type(dic)

dict

In [125]:
dic={1,2,3,4,5}

In [126]:
type(dic)

set

In [128]:
my_dict={"car1":"audi","car2":"bmw","car3":"mercedes"}

In [129]:
my_dict

{'car1': 'audi', 'car2': 'bmw', 'car3': 'mercedes'}

In [130]:
my_dict['car1'] #Access the value based on keys

'audi'

In [131]:
#We can even loop throught the dictonary keys

In [132]:
for x in my_dict:
    print(x)  #to retrieve keys

car1
car2
car3


In [134]:
#if want to retrive values
for x in my_dict.values():
    print(x)

audi
bmw
mercedes


In [135]:
#We can also check all values and keys 
for x in my_dict.items():
    print(x)

('car1', 'audi')
('car2', 'bmw')
('car3', 'mercedes')


In [136]:
#Adding items in Dictionaries
my_dict['car4']='Audi 2.0'

In [137]:
my_dict

{'car1': 'audi', 'car2': 'bmw', 'car3': 'mercedes', 'car4': 'Audi 2.0'}

Nested Dictionary

In [140]:
car1_model={'Mercedes':1960}
Car2_model={'Audi':1970}
Car3_model={'Mercedes Benz'}
car_type={'car1':car1_model,'car2':Car2_model,'car3':Car3_model}

In [141]:
print(car_type)

{'car1': {'Mercedes': 1960}, 'car2': {'Audi': 1970}, 'car3': {'Mercedes Benz'}}


In [142]:
#Accessing the items in the dictionary
print(car_type['car1'])

{'Mercedes': 1960}


In [143]:
print(car_type['car1']['Mercedes'])

1960


Tuples

In [144]:
#Use very wisely as its not mutable once defined that is fixed 
my_tuple=tuple()

In [145]:
type(my_tuple)

tuple

In [146]:
my_tuple=("aditya","singh","rajput")

In [147]:
my_tuple[0]

'aditya'

In [148]:
print(type(my_tuple))
print(my_tuple)

<class 'tuple'>
('aditya', 'singh', 'rajput')


In [149]:
my_tuple[0]="Raju" #Means tuple cant support mutation of element

TypeError: 'tuple' object does not support item assignment

In [150]:
my_tuple=("aditya","Kumar","rajput") #All value we can reassign but within that element is not mutable at all

In [151]:
my_tuple.count('aditya')

1

In [152]:
my_tuple.index('aditya')

0

Numpy Tutorials


NumPy Is a general-purpose array-processing package. It provides a high-performance muitidimensional array object, and
tools for working with these arrays. It is the fundamental package for scientific computing with Python


What is an array


An array Is a data structure that stores values of same data type. In Python, this is the main difference between arrays and
lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values
corresponding to same data type

In [153]:
import numpy as np

In [154]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [156]:
type(arr)

numpy.ndarray

In [157]:
print(arr)

[1 2 3 4 5]


In [158]:
arr.shape

(5,)

In [159]:
arr  

array([1, 2, 3, 4, 5])

In [160]:
arr.shape 

(5,)

In [161]:
# Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,91]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [162]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 9,  7,  6,  8, 91]])

In [164]:
arr.shape

(3, 5)

In [165]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 3,  4,  5],
       [ 6,  9,  7],
       [ 6,  8, 91]])

In [166]:
arr.shape

(3, 5)

In [167]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

Indexing

In [168]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 9,  7,  6,  8, 91]])

In [169]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [171]:
arr[2]

array([ 9,  7,  6,  8, 91])

In [172]:
arr[1:,3:]

array([[ 5,  6],
       [ 8, 91]])

In [ ]:
#Lets understand what happened above
#arr[:,:]-means will pick all row before comma means and after commaa will pick all column lets try

In [173]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 9,  7,  6,  8, 91]])

In [174]:
arr[1:,2:] #Mean will pick first index row and then 2  to all index column

array([[ 4,  5,  6],
       [ 6,  8, 91]])

In [175]:
arr[:,3:]

array([[ 4,  5],
       [ 5,  6],
       [ 8, 91]])

In [176]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [177]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [179]:
arr=np.arange(0,10)

In [180]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
arr=np.arange(0,10,step=2)

In [182]:
arr

array([0, 2, 4, 6, 8])

In [183]:
arr[3:]=100

In [184]:
arr

array([  0,   2,   4, 100, 100])

In [185]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [186]:
arr1=arr.copy()

In [187]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 100 100]
[   0    2    4 1000 1000]


Lets Practice 50+ Numpy Practice Question

In [189]:
#Exercise 1. Import numpy as np and see the version
import numpy as np
print (np.__version__)

2.0.1


In [191]:
#Exercise 2. How to create a 1D array?

# Question : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
#Exercise 3. How to create a boolean array?
# Question : Create a 3×3 numpy array of all True’s

# Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [200]:
#To extract all odd number from array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [204]:
#Exercise 5. How to replace items that satisfy a condition with another value in numpy array?
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [205]:
#Exercise 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)

In [206]:
out=arr.copy()

In [207]:
out[out%2 == 1] = -1

In [211]:
print('Modified Array')
out


Modified Array


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [212]:
print('\nOriginal Array')
arr


Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
print('Modified Array')
print(out)
print('\nOriginal Array')
print(arr)

Modified Array
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array
[0 1 2 3 4 5 6 7 8 9]


In [216]:
#Exercise 7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [217]:
arr = np.arange(10)
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [218]:
"""
The reshape function is used to change the shape of the array.
In this case, you want to reshape the array into 2 rows.
The -1 is a special value that tells NumPy to automatically figure out 
the number of columns based on the total number of elements and the number of rows you specified.

Since the original array has 10 elements, and you want 2 rows, 
NumPy will calculate that each row should have 5 columns to accommodate all 10 elements.
"""
arr = np.arange(10)
arr.reshape(2, -1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [219]:
#Exercise 8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [220]:
#How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [221]:
#Exercise 10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [222]:
np.hstack((np.repeat(a, 3), np.tile(a, 3)))#Other way

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [223]:
#Exercise 11. How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [224]:
#Exercise 12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [225]:
#Exercise 13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [226]:
#Exercise 14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [230]:
#Exercise 15. How to make a python function that handles scalars to work on numpy arrays?
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
def pair_max(x, y):
    # Using map to make pairs of elements from x and y, then applying maxx function to each pair
    maximum = [maxx(a, b) for a, b in map(lambda a, b: (a, b), x, y)]
    # Alternative approach using zip (more common and simpler)
    # maximum = [maxx(a, b) for a, b in zip(x, y)]
    return np.array(maximum)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)


array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
"""
### Function Definition
The `pair_max` function is designed to find the element-wise maximum between two arrays. Here’s the full code with comments:

```python
def pair_max(x, y):
    # Using map to make pairs of elements from x and y, then applying maxx function to each pair
    maximum = [maxx(a, b) for a, b in map(lambda a, b: (a, b), x, y)]
    # Alternative approach using zip (more common and simpler)
    # maximum = [maxx(a, b) for a, b in zip(x, y)]
    return np.array(maximum)
```

### Step-by-Step Explanation

#### 1. Input Arrays `x` and `y`
The function expects two arrays as input. Let's say you have:

```python
x = np.array([5, 7, 9, 8, 6, 4, 5])
y = np.array([6, 3, 4, 8, 9, 7, 1])
```

#### 2. Pairing Elements Using `map` and `lambda`
The `map` function is used to create pairs of corresponding elements from the two arrays `x` and `y`.

- **`lambda a, b: (a, b)`**: This is a small anonymous function (a `lambda` function) that takes two arguments `a` and `b` and returns them as a tuple `(a, b)`. 

- **`map(lambda a, b: (a, b), x, y)`**: This applies the `lambda` function to each pair of elements from `x` and `y`. 

   - For example, the first elements of `x` and `y` are `5` and `6`. The `lambda` function pairs them as `(5, 6)`.
   - The second elements `7` (from `x`) and `3` (from `y`) are paired as `(7, 3)`.
   - This process continues for all elements.

The result of `map(lambda a, b: (a, b), x, y)` is an iterator that produces these pairs:

```python
[(5, 6), (7, 3), (9, 4), (8, 8), (6, 9), (4, 7), (5, 1)]
```

#### 3. List Comprehension to Apply `maxx`
Now, we use a list comprehension to find the maximum value for each pair produced by `map`.

```python
maximum = [maxx(a, b) for a, b in map(lambda a, b: (a, b), x, y)]
```

- **`for a, b in map(lambda a, b: (a, b), x, y)`**: This part extracts each pair `(a, b)` from the `map` object.
- **`maxx(a, b)`**: For each pair `(a, b)`, the `maxx` function is called to find the maximum value. 

   - If `a = 5` and `b = 6`, `maxx(5, 6)` will return `6`.
   - This continues for all pairs, resulting in a list of maximum values:
  
```python
maximum = [6, 7, 9, 8, 9, 7, 5]
```

#### 4. Converting the List to a NumPy Array
Finally, the list of maximum values is converted into a NumPy array:

```python
return np.array(maximum)
```

This step turns the list `[6, 7, 9, 8, 9, 7, 5]` into a NumPy array:

```python
array([6, 7, 9, 8, 9, 7, 5])
```

### Alternative Approach: Using `zip`
The code also suggests an alternative, simpler way to pair elements using `zip`:

```python
# maximum = [maxx(a, b) for a, b in zip(x, y)]
```

- **`zip(x, y)`**: This function pairs elements from `x` and `y` just like `map` does.
- **`maxx(a, b) for a, b in zip(x, y)`**: This applies the `maxx` function to each pair and creates a list of maximum values.

The final result will be the same, but using `zip` is often preferred because it's more straightforward and commonly used in Python for such tasks.

### Summary
- The function `pair_max` compares elements from two arrays one by one and returns a new array containing the maximum value from each comparison.
- The process involves pairing elements, comparing them using the `maxx` function, and then converting the list of results into a NumPy array.
- An alternative approach using `zip` instead of `map` is also suggested, which accomplishes the same task in a more common and simpler way."""

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

: 